service: ml-model-as-an-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  lambdaHashingVersion: '20201221'

functions:
  basic:
    handler: src/main.hello
    name: basic-api
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: /
          method: get